/*
 * This source file was generated by the Gradle 'init' task
 */
package org.com.taro;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@SpringBootApplication
@EnableJpaRepositories(basePackages = "org.com.taro.repository")
public class App {
    public String getGreeting() {
        return "Hello World!!!";
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}

println("error test");
